import jsPDF from "jspdf";

type CompanyInfo = {
  name: string;
  addressLines: string[];
  phone?: string;
  email?: string;
  website?: string;
};

export const generateJoiningFormPDF = () => {
  const doc = new jsPDF("p", "mm", "a4");

  // ===== PAGE CONSTANTS =====
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 16;
  const marginR = 16;
  const contentW = pageW - marginL - marginR;
  const topMargin = 16;
  const bottomMargin = 16;

  let y = topMargin;

  // ===== COMPANY CONFIG =====
  const company: CompanyInfo = {
    name: "RS-FISHERIES",
    addressLines: [
      "D.No 26-2-1272, Shankaran Colony",
      "Near Ayyappa Temple, GNT Road",
      "Nellore - 524004",
    ],
    phone: "+91 98765 43210",
    email: "info@rsfisheries.com",
    website: "www.rsfisheries.com",
  };

  // ===== STYLES & FONT HELPERS =====
  const fontRegular = (size = 11) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
  };
  const fontBold = (size = 11) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
  };
  const fontItalic = (size = 10) => {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(size);
  };

  const setBody = () => fontRegular(11);
  const setLabel = () => fontBold(10.5);
  const setSmall = () => fontRegular(9.0);

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - bottomMargin) {
      addFooter();
      doc.addPage();
      y = topMargin;
      drawHeaderCompact(); // re-draw a compact header on new page
    }
  };

  // ===== COLOR & SHADOW UTILS =====
  const ACCENT = { r: 20, g: 90, b: 170 }; // modern blue accent
  const SOFT_BG = { r: 244, g: 248, b: 255 };
  const SOFT_GREY = { r: 230, g: 230, b: 230 };

  // ===== HEADER (Prominent) =====
  const logoSize = 44;
  const logoX = marginL;
  const logoY = topMargin;

  const drawHeader = () => {
    // left logo (attempt, wrapped in try/catch)
    try {
      // Use path /favicon.jpg or adjust as needed. If not found, it'll be ignored.
      doc.addImage("/favicon.jpg", "JPEG", logoX, logoY, logoSize, logoSize);
    } catch (e) {
      // draw placeholder rounded square for logo
      doc.setDrawColor(210);
      doc.setFillColor(245, 245, 245);
      doc.rect(logoX, logoY, logoSize, logoSize, "FD");
      fontBold(12);
      doc.setTextColor(ACCENT.r, ACCENT.g, ACCENT.b);
      doc.text("RS", logoX + logoSize / 2, logoY + logoSize / 2 + 4, {
        align: "center",
      });
      doc.setTextColor(0);
    }

    // company block (right side)
    const rightBlockX = logoX + logoSize + 8;
    const rightBlockW = contentW - logoSize - 8;
    fontBold(18);
    doc.setTextColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.text(company.name, pageW - marginR, logoY + 10, { align: "right" });

    doc.setTextColor(80);
    setSmall();
    let cy = logoY + 16;
    company.addressLines.forEach((line) => {
      doc.text(line, pageW - marginR, cy, { align: "right" });
      cy += 4.8;
    });

    if (company.phone) {
      doc.text(`T: ${company.phone}`, pageW - marginR, cy, { align: "right" });
      cy += 4.8;
    }
    if (company.email) {
      doc.text(company.email, pageW - marginR, cy, { align: "right" });
      cy += 4.8;
    }
    if (company.website) {
      doc.text(company.website, pageW - marginR, cy, { align: "right" });
      cy += 4.8;
    }

    // Title card
    y = logoY + logoSize + 8;
    const titleH = 14;
    doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.rect(marginL, y - 6, contentW, titleH, "F");
    fontBold(13);
    doc.setTextColor(255, 255, 255);
    doc.text("EMPLOYEE JOINING FORM", pageW / 2, y + 4, { align: "center" });
    doc.setTextColor(0);
    y += titleH + 6;
  };

  // compact header for new pages to keep continuity
  const drawHeaderCompact = () => {
    fontBold(11);
    doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.rect(marginL, topMargin - 2, 40, 10, "F");
    doc.setTextColor(255, 255, 255);
    doc.text("RS", marginL + 20, topMargin + 5, { align: "center" });
    doc.setTextColor(0);
    fontBold(11);
    doc.text(company.name, marginL + 48, topMargin + 5);
    y = topMargin + 14;
  };

  // ===== FOOTER =====
  const addFooter = () => {
    const footerY = pageH - bottomMargin + 6;
    doc.setDrawColor(240);
    doc.setLineWidth(0.4);
    doc.line(marginL, footerY - 6, pageW - marginR, footerY - 6);
    setSmall();
    doc.setTextColor(110);
    doc.text(
      `Generated by RS-Fisheries • ${company.website ?? ""}`,
      marginL,
      footerY - 1
    );
    const pageNumber = doc.getNumberOfPages();
    doc.text(`Page ${pageNumber}`, pageW - marginR, footerY - 1, {
      align: "right",
    });
    doc.setTextColor(0);
  };

  // ===== SECTION CARD HELPER =====
  const sectionCard = (title: string, accentLeft = true) => {
    ensureSpace(18);
    const cardH = 11;
    // header strip
    if (accentLeft) {
      doc.setFillColor(SOFT_BG.r, SOFT_BG.g, SOFT_BG.b);
      doc.rect(marginL, y, contentW, cardH, "F");
      doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
      doc.rect(marginL, y, 6, cardH, "F");
      fontBold(11);
      doc.setTextColor(20, 30, 50);
      doc.text(title, marginL + 12, y + 8);
    } else {
      doc.setFillColor(SOFT_BG.r, SOFT_BG.g, SOFT_BG.b);
      doc.rect(marginL, y, contentW, cardH, "F");
      doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
      doc.rect(marginL + contentW - 6, y, 6, cardH, "F");
      fontBold(11);
      doc.setTextColor(20, 30, 50);
      doc.text(title, marginL + 6, y + 8);
    }
    doc.setTextColor(0);
    y += cardH + 6;
  };

  // ===== FIELD DRAW HELPERS =====
  const fieldLine = (x: number, yy: number, w: number, h = 9) => {
    doc.setDrawColor(200);
    doc.setLineWidth(0.35);
    doc.rect(x, yy - 7, w, h, "S");
  };

  const fieldLabel = (text: string, x: number, yy: number) => {
    setLabel();
    doc.setTextColor(70);
    doc.text(text, x, yy);
    setBody();
    doc.setTextColor(0);
  };

  const inputBox = (
    x: number,
    yy: number,
    w: number,
    label?: string,
    h = 10
  ) => {
    if (label) {
      fieldLabel(label, x + 2, yy + 3);
    }
    fieldLine(x, yy + 6, w, h);
  };

  const twoCol = (leftLabel: string, rightLabel: string, h = 10) => {
    ensureSpace(h + 12);
    const gap = 8;
    const colW = (contentW - gap) / 2;
    inputBox(marginL, y, colW, leftLabel, h);
    inputBox(marginL + colW + gap, y, colW, rightLabel, h);
    y += h + 12;
  };

  const threeCol = (a: string, b: string, c: string, h = 9) => {
    ensureSpace(h + 12);
    const gap = 6;
    const colW = (contentW - gap * 2) / 3;
    inputBox(marginL, y, colW, a, h);
    inputBox(marginL + colW + gap, y, colW, b, h);
    inputBox(marginL + (colW + gap) * 2, y, colW, c, h);
    y += h + 12;
  };

  const fullWidth = (label: string, h = 12) => {
    ensureSpace(h + 12);
    inputBox(marginL, y, contentW, label, h);
    y += h + 12;
  };

  // stylized checkbox row (modern chips)
  const checkboxChips = (items: string[]) => {
    ensureSpace(22);
    const chipH = 8;
    const gapX = 6;
    let x = marginL;
    items.forEach((t) => {
      const textW = doc.getTextWidth(t) + 6;
      const chipW = textW + 12;
      if (x + chipW > pageW - marginR) {
        y += chipH + 6;
        x = marginL;
      }
      // chip outline
      doc.setDrawColor(200);
      doc.setLineWidth(0.4);
      doc.roundedRect(x, y - 6, chipW, chipH, 1.5, 1.5, "S");
      // small checkbox inside chip
      doc.rect(x + 2, y - 5.5, 4.5, 4.5, "S");
      setSmall();
      doc.text(t, x + 10, y - 0.5);
      setBody();
      x += chipW + gapX;
    });
    y += 14;
  };

  // table with header shading
  const table = (
    headers: string[],
    colWidths: number[],
    rows: number,
    rowH = 10
  ) => {
    const headerH = 10;
    const totalH = headerH + rows * rowH + 8;
    ensureSpace(totalH);

    let x = marginL;

    // header
    doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.setDrawColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.setTextColor(255);
    fontBold(10);
    for (let i = 0; i < headers.length; i++) {
      doc.rect(x, y, colWidths[i], headerH, "F");
      doc.text(headers[i], x + 3, y + 7);
      x += colWidths[i];
    }
    y += headerH;

    // rows
    doc.setTextColor(0);
    fontRegular(10);
    doc.setDrawColor(200);
    for (let r = 0; r < rows; r++) {
      x = marginL;
      // alternating very soft fill
      if (r % 2 === 1) {
        doc.setFillColor(SOFT_GREY.r, SOFT_GREY.g, SOFT_GREY.b);
        doc.rect(
          marginL,
          y,
          colWidths.reduce((a, b) => a + b, 0),
          rowH,
          "F"
        );
      }
      for (let i = 0; i < headers.length; i++) {
        doc.rect(x, y, colWidths[i], rowH, "S");
        x += colWidths[i];
      }
      y += rowH;
    }
    y += 8;
  };

  // photo box modern
  const photoBox = (x: number, yy: number, w: number, h: number) => {
    doc.setDrawColor(190);
    doc.setLineWidth(0.5);
    doc.rect(x, yy, w, h, "S");
    fontBold(9);
    doc.setTextColor(110);
    doc.text("PHOTO", x + w / 2, yy + 6, { align: "center" });
    setBody();
  };

  // ===== DRAW THE FORM =====
  // header
  drawHeader();

  // Employment details
  sectionCard("Employment Details");
  threeCol("Employee ID", "Date of Joining (DOJ)", "Employment Type");
  threeCol("Department", "Designation", "Work Location");
  twoCol("Reporting Manager", "CTC / Monthly Salary");

  // Personal Details
  sectionCard("Personal Details");
  ensureSpace(80);

  const photoW = 46;
  const photoH = 58;
  const photoX = pageW - marginR - photoW;

  photoBox(photoX, y, photoW, photoH);

  // Full name and top-aligned fields
  const nameW = contentW - photoW - 10;
  inputBox(marginL, y, nameW, "Full Name (as per Aadhaar):", 12);
  y += 18;
  inputBox(marginL, y, nameW, "Father’s Name:", 12);
  y += 18;
  inputBox(marginL, y, nameW, "Mother’s Name (optional):", 12);
  y += 18;
  threeCol("Gender", "Date of Birth", "Blood Group");
  threeCol("Marital Status", "Nationality", "Religion (optional)");
  fullWidth("Identification Mark 1 (optional):", 12);
  fullWidth("Identification Mark 2 (optional):", 12);
  fullWidth("Correspondence Address:", 20);
  fullWidth("Permanent Address:", 20);
  threeCol("Telephone (Landline)", "Mobile", "Email ID");
  twoCol("PAN Card No", "Aadhaar No");

  // Emergency contact
  sectionCard("Emergency Contact Details");
  threeCol("Contact Name", "Relation", "Primary Contact No");
  twoCol("Alternate Contact No", "Emergency Email (optional)");
  fullWidth("Emergency Contact Address:", 18);

  // Education
  sectionCard("Educational Details");
  table(
    [
      "Degree",
      "University / Institute",
      "From",
      "To",
      "% / CGPA",
      "Specialization",
    ],
    [34, 62, 22, 22, 30, 45],
    4
  );

  // Employment / Experience
  sectionCard("Employment / Experience Details (If applicable)");
  twoCol("Total Experience", "Last Employer Name");
  twoCol("Last Designation", "Last Drawn Salary");
  fullWidth("Reason for Leaving:", 16);

  // Bank & Statutory
  sectionCard("Bank & Statutory Details");
  twoCol("Bank Name", "Branch");
  twoCol("Account Number", "IFSC Code");
  threeCol("UAN (PF)", "PF No (if any)", "ESI No (if any)");

  // Family
  sectionCard("Family Details");
  table(
    ["Name", "Relation", "DOB", "Occupation", "Mobile"],
    [62, 36, 26, 52, 32],
    3
  );

  // Nominee
  sectionCard("Nominee Details (PF / Gratuity / Insurance)");
  twoCol("Nominee Name", "Relation");
  threeCol("Nominee DOB", "Nominee Mobile", "Nominee Aadhaar (optional)");
  fullWidth("Nominee Address:", 18);

  // References
  sectionCard("References (2 Contacts)");
  table(["Name", "Company / Relation", "Mobile", "Email"], [68, 64, 36, 48], 2);

  // Documents checklist
  sectionCard("Documents Submitted (Checklist)");
  checkboxChips([
    "Aadhaar Copy",
    "PAN Copy",
    "Passport Photo (2)",
    "Bank Passbook / Cancelled Cheque",
    "Education Certificates",
    "Experience Letter (if any)",
    "Relieving Letter (if any)",
    "Salary Slips (last 3 months)",
    "Address Proof",
  ]);

  // Declaration & Terms
  sectionCard("Declaration & Terms and Conditions", false);
  ensureSpace(100);

  // Declaration box
  doc.setDrawColor(200);
  doc.setLineWidth(0.35);
  const declBoxH = 86;
  doc.rect(marginL, y, contentW, declBoxH, "S");

  setBody();
  doc.setTextColor(40);
  const declLines = [
    "I hereby declare that the information provided in this form is true, accurate, and complete to the best of my knowledge and belief.",
    "",
    "I understand that any misrepresentation, omission, or false information may result in disqualification from employment or immediate termination.",
    "",
    "I authorize RS-Fisheries to verify the provided information and conduct background checks, including education, previous employment, and references.",
    "",
    "I agree to abide by all company policies, rules, regulations, code of conduct, and any amendments thereof during my employment.",
    "",
    "I consent to the collection, processing, and storage of my personal data for employment purposes in compliance with applicable data protection laws.",
    "",
    "I understand that my employment is subject to satisfactory completion of reference checks, background verification, and medical fitness (if required).",
    "",
    "I agree that the company reserves the right to modify terms of employment with due notice.",
    "",
    "In case of any dispute arising out of employment, the jurisdiction shall be Nellore courts only.",
  ];

  let declY = y + 8;
  fontRegular(10);
  declLines.forEach((line) => {
    if (line === "") {
      declY += 6;
    } else {
      doc.text(line, marginL + 6, declY, { maxWidth: contentW - 12 });
      declY += 6.8;
    }
  });

  y += declBoxH + 12;

  // Signatures area
  ensureSpace(48);
  const sigW = 72;
  const sigH = 14;

  // Employee signature (left)
  doc.setDrawColor(170);
  doc.setLineWidth(0.35);
  const empSigX = marginL + 12;
  doc.line(empSigX, y + 18, empSigX + sigW, y + 18);
  setSmall();
  doc.text("Employee Signature", empSigX + sigW / 2, y + 22, {
    align: "center",
  });

  // Date & Place (left underneath)
  setSmall();
  doc.text("Date:", empSigX - 6, y + 8);
  doc.line(empSigX + 10, y + 8, empSigX + 54, y + 8);
  doc.text("Place:", empSigX - 6, y + 14);
  doc.line(empSigX + 10, y + 14, empSigX + 54, y + 14);

  // HR / Authorized Signatory (right)
  const hrSigX = pageW - marginR - sigW - 12;
  doc.line(hrSigX, y + 18, hrSigX + sigW, y + 18);
  setSmall();
  doc.text("HR / Authorized Signatory", hrSigX + sigW / 2, y + 22, {
    align: "center",
  });

  // ----- final footer and save
  addFooter();
  doc.save("RS-Fisheries_Employee_Joining_Form.pdf");
};
